# -*- coding: utf-8 -*-
"""Sistema de Auditoria de  Recursos Coporativos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HySJSq5d9swpU1oVctjcdrPkcEUo8c6t

#Sistema de Auditoria de Recursos Corporativos

> Adicionar aspas



####Leonardo Alves Tavares Calixta
"""

empresa_data = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 50000,
                "Seguranca": 30000
            },
            "Desenvolvimento": {
                "Frontend": 20000,
                "Backend": 25000,
                "DevOps": 15000
            }
        },
        "RH": {
            "Recrutamento": 10000,
            "Treinamento": 12000,
            "Cultura": {
                "Eventos": 5000,
                "Brindes": 2000
            }
        },
        "Financeiro": 40000
    }
}

import time

TAXA_PADRAO = 1.0
MOEDA_PADRAO = "USD"


# Decorator
def auditor(funcao_original):
    def auditar(*args, **kwargs):
        print("=" * 60)
        print("INICIANDO AUDITORIA")
        print("=" * 60)
        print(f"args: {args}")
        print(f"kwargs: {kwargs}")
        print("-" * 60)

        inicio = time.time()
        resultado = funcao_original(*args, **kwargs)
        fim = time.time()

        print("-" * 60)
        print(f"Tempo de execução: {fim - inicio:.6f} segundos")
        print("=" * 60)
        return resultado
    return auditar


# Função recursiva
def calcular_orcamento_recursivo(arvore, *deptos_ignorados):
    soma = 0
    for nome_depto, valor in arvore.items():
        if nome_depto in deptos_ignorados:
            continue
        # Caso Recursivo
        if type(valor) == dict:
            soma_sub = calcular_orcamento_recursivo(valor, *deptos_ignorados)
            soma = soma + soma_sub
        else:
            # Caso base
            soma = soma + valor
    return soma


@auditor
def calcular_orcamento(arvore, *deptos_ignorados, **parametros_cambio):
    soma_total = calcular_orcamento_recursivo(arvore, *deptos_ignorados)

    moeda = MOEDA_PADRAO
    taxa = TAXA_PADRAO
    if "moeda_destino" in parametros_cambio:
        moeda = parametros_cambio["moeda_destino"]
    if "taxa_cambio" in parametros_cambio:
        taxa = parametros_cambio["taxa_cambio"]

    soma_convertida = soma_total * taxa

    print(f"Soma original (USD): {soma_total:.2f}")
    print(f"Moeda destino: {moeda}")
    print(f"Taxa: {taxa}")
    print(f"Valor final: {moeda} {soma_convertida:.2f}")

    return soma_convertida

# Teste 1: orçamento total
calcular_orcamento(empresa_data)

# Teste 2: ignorando departamentos
calcular_orcamento(empresa_data, "Cultura", "Desenvolvimento")

# Teste 3: convertendo para BRL
calcular_orcamento(empresa_data, moeda_destino="BRL", taxa_cambio=5.20)