"""Smile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRJl6AwQe24uNOgfF2IqF7wJkpedxSiu
"""

import matplotlib.pyplot as plt

emoji_data = {
    "nome": "Smile",
    "grade": [
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0
        [(255,255,0), (0,0,0),     (255,255,0), (0,0,0),     (255,255,0)], # Linha 1 (Olhos)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2
        [(255,255,0), (0,0,0),     (0,0,0),     (0,0,0),     (255,255,0)], # Linha 3 (Boca)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]  # Linha 4
    ]
}

nova_grade = []

# Nível 1: Percorrendo o Dicionário (Lote)
for chave, valor in emoji_data.items():
    if chave == "grade":
        # Nível 2: Percorrendo as Linhas
        for linha in valor:
            nova_linha = []
            # Nível 3: Percorrendo os Pixels
            for pixel in linha:
                # Lógica do Filtro: Se for Amarelo (255, 255, 0)
                if pixel == (255, 255, 0):
                    # Criando nova tupla com brilho reduzido (50%)
                    pixel_sombreado = (pixel[0] // 2, pixel[1] // 2, pixel[2] // 2)
                    nova_linha.append(pixel_sombreado)
                else:
                    # Se for preto (ou outra cor), mantém original
                    nova_linha.append(pixel)

            nova_grade.append(nova_linha)

# Atualizando o dicionário original com a nova grade
emoji_data["grade"] = nova_grade

# Print para conferir o resultado
print(f"Emoji: {emoji_data['nome']}")
for linha in emoji_data["grade"]:
    print(linha)

plt.imshow(emoji_data["grade"])
plt.show()
