# -*- coding: utf-8 -*-
"""Traduzindo lógiva para python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKQD7Fdjzxj7Ui8N3f8yyAmyQE6pWwjJ

# Nova seção
"""

# Função 1 - processar_vendas

def processar_vendas():
  total_compra = 0.0
  itens_comprados = 0
  quantidade_tipos = int(input("Quantos produtos diferentes foram comprados? "))

  for i in range(1, quantidade_tipos + 1):
    nome = input("Nome do produto: ")
    preco = float(input("Preço unitário: "))
    qtd = int(input("Quantidade deste produto: "))

    if preco <= 0 or qtd <= 0:
      print("Erro: Valores inválidos para", nome)
    else:
      subtotal = preco * qtd
      total_compra = total_compra + subtotal
      itens_comprados = itens_comprados + qtd

  if total_compra > 500.00:
    total_final = total_compra * 0.90
    print("Desconto de 10% aplicado!")
  elif total_compra > 200.00:
    total_final = total_compra * 0.95
  else:
    total_final = total_compra
  print("Resumo:", itens_comprados, "itens. Total a pagar: R$", total_final)

processar_vendas()

2# Função 2 - analisar_clima

def analisar_clima():
  soma_temperaturas = 0.0
  dias_quentes = 0
  alerta_extremo = False

  for dia in range(1, 8):
    temp = float(input("Digite a temperatura do dia " + str(dia) + ": "))
    soma_temperaturas = soma_temperaturas + temp
    if temp > 35.0:
      dias_quentes = dias_quentes + 1
    if temp > 45.0 or temp < -5.0:
      alerta_extremo = True
  media = soma_temperaturas / 7
  print("Média semanal:", media)
  print("Dias acima de 35°C:", dias_quentes)

  if alerta_extremo == True:
    print("CUIDADO: Condições climáticas perigosas detectadas!")
  else:
    print("Clima dentro da normalidade operacional.")

analisar_clima()

# Função 3 - sistema_notas_turma

def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos existem na turma? "))

  for j in range(1, total_alunos + 1):

    aluno_nome = input("Nome do aluno: ")
    n1 = float(input("Nota 1: "))
    n2 = float(input("Nota 2: "))
    media_aluno = (n1 + n2) / 2

    if media_aluno >= 7.0:
      print(aluno_nome, ": Aprovado com média", media_aluno)
    elif media_aluno >= 5.0:
      print(aluno_nome, ": Recuperação (Média:", media_aluno, ")")
    else:
      print(aluno_nome, ": Reprovado")

sistema_notas_turma()