# -*- coding: utf-8 -*-
"""Atividade Auditoria de Vendas Semanais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FFzA691V0vPgaEUcTV6AfYQiGp6pQFr
"""

# Auditoria de Vendas Semanais

Limite_Segurança = 1000.00
analisar_vendas = print(f"Análise de vendas: ")
espaço_final = print(f"."*50)

 #Vendas Semanais

num1 = float(input("Venda 01: "))
num2 = float(input("Venda 02: "))
num3 = float(input("Venda 03: "))

 #Cálculo

soma  = num1 + num2 + num3
media = soma / 3
print(f"."*50)
print("Media das Vendas:" , media)
print(f"."*50)

 # Verificação
def analisar_vendas():
  print(analisar_vendas)
def espaço_final():
  print(espaço_final)
if media <= Limite_Segurança:
  print(f"Limite de Segurança Atingido.")
else:
  print(f"SISTEMA EM QUARENTENA:")
if media > Limite_Segurança:
  print(f"REVISÃO MANUAL NECESSÁRIA!")
print(f"."*50)

#Processamento