# -*- coding: utf-8 -*-
"""Engenharia de Contexto e Lógica Física

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxu-M97a84U9TcFD5JIzEF8uhlrWUb14
"""

# PARTE 1: Algoritmo do Microclima Local

def analisar_microclima():
    dados_locais = [
        ["São Paulo",  "15h", 27.0, 57.0, 61],
        ["São Paulo",  "18h", 22.0, 45.0, 61],
        ["Santos",     "15h", 26.0, 54.0, 67],
        ["Santos",     "18h", 24.0, 58.0, 68],
        ["Campinas",   "15h", 27.0, 42.0, 81],
        ["Campinas",   "18h", 23.0, 53.0, 84],
    ]

    cabecalhos = ["Local", "Horário", "Temp (°C)", "Umidade (%)", "IQA"]

    print("=" * 70)
    print("       ANÁLISE DE MICROCLIMA URBANO — SÃO PAULO")
    print("=" * 70)

    for registro in dados_locais:
        local, horario, temp, umidade, iqa = registro
        metricas = [local, horario, temp, umidade, iqa]

        print(f"\nLocal: {local} — {horario}")
        print("-" * 50)

        # FOR interno com enumerate (substituindo range/len)
        for i, metrica in enumerate(metricas[2:], start=2):
            print(f"  {cabecalhos[i]}: {metrica}")

        # --- Classificação por match-case (IQA — faixas oficiais CETESB) ---
        match True:
            case _ if iqa <= 40:
                qualidade = "Boa"
                risco = "Sem risco à saúde."
            case _ if iqa <= 80:
                qualidade = "Moderada"
                risco = "Risco para grupos sensíveis (idosos, crianças, asmáticos)."
            case _ if iqa <= 120:
                qualidade = "Ruim"
                risco = "Risco à saúde da população em geral."
            case _ if iqa <= 200:
                qualidade = "Muito Ruim"
                risco = "Risco sério à saúde. Evitar atividades ao ar livre."
            case _:
                qualidade = "Péssima"
                risco = "Risco gravíssimo. Emergência de saúde pública."

        print(f"  Qualidade do Ar: {qualidade}")
        print(f"  Risco: {risco}")

        # -------------------------------------------------------------------
        # NOTA DE CONFORTO URBANO -> 0 a 10 <-
        #
        # Fórmula:
        #   nota_temp    = penaliza temperaturas abaixo de 18°C ou acima de 26°C
        #                  usando distância quadrática normalizada
        #
        #   nota_umidade = máximo de conforto entre 50-70%; penaliza extremos
        #
        #   nota_iqa     = escala invertida: IQA 0 -> 10pts, IQA 120+ -> 0pts
        #
        #   Nota Final = (nota_temp * 0.35) + (nota_umidade * 0.25) + (nota_iqa * 0.40)
        # -------------------------------------------------------------------

        # Penalidade de temperatura: ideal entre 18-26°C
        temp_ideal_min = 18
        temp_ideal_max = 26

        if temp_ideal_min <= temp <= temp_ideal_max:
            nota_temp = 10.0
        else:
            desvio = min(abs(temp - temp_ideal_min), abs(temp - temp_ideal_max))
            nota_temp = max(0, 10 - (desvio ** 1.5))

        # Nota de umidade: ideal entre 50-70%
        umid_ideal_min = 50
        umid_ideal_max = 70

        if umid_ideal_min <= umidade <= umid_ideal_max:
            nota_umidade = 10.0
        else:
            desvio_u = min(abs(umidade - umid_ideal_min), abs(umidade - umid_ideal_max))
            nota_umidade = max(0, 10 - (desvio_u * 0.25))

        # Nota IQA: escala invertida linear (0=10pts, 120=0pts)
        nota_iqa = max(0, 10 - (iqa / 12))

        # Nota final ponderada
        nota_conforto = (nota_temp * 0.35) + (nota_umidade * 0.25) + (nota_iqa * 0.40)
        nota_conforto = round(nota_conforto, 2)

        # Parametros de conforto
        if nota_conforto >= 8:
            conceito = "Excelente"
        elif nota_conforto >= 6:
            conceito = "Bom"
        elif nota_conforto >= 4:
            conceito = "Regular"
        else:
            conceito = "Desconfortável"

        print(f"  Nota de Conforto Urbano: {nota_conforto}/10 — {conceito}")

    print("\n" + "=" * 70)
    print("Análise concluída.")
    print("=" * 70)

analisar_microclima()

# PARTE 2: Simulador de Evacuação

def simular_evacuacao():

    locais = [
        "Quarto dos fundos",
        "Corredor principal",
        "Cozinha",
        "Sala de estar",
        "Hall de entrada",
        "Saída (Rua)"
    ]

    estados = [
        "chave disponivel",
        "porta trancada",
        "extintor disponivel",   # <- extintor ANTES da fumaça
        "fumaca",
        "caminho livre",
        "saida"
    ]

    inventario = []
    energia = float(10.0)
    posicao = 0

    print("=" * 50)
    print("   SIMULADOR DE EVACUAÇÃO DE EMERGÊNCIA")
    print("=" * 50)
    print(f"Agente inicia em: {locais[posicao]}")
    print(f"Energia disponível: {energia:.0f}")
    print()

    while energia > 0 and posicao < len(locais) - 1:

        local_atual = locais[posicao]
        obstaculo   = estados[posicao]

        print(f"Posição atual: {local_atual}")
        print(f"    Situação aqui: {obstaculo}")

        if obstaculo == "chave disponivel":
            print("    Agente encontrou uma chave! Coleta e avança.")
            inventario.append("chave")
            posicao += 1

        elif obstaculo == "porta trancada":
            if "chave" in inventario:
                print("    Porta trancada! Agente usa a chave e passa.")
                inventario.remove("chave")
                posicao += 1
                energia -= 1.0
            else:
                print("    Porta trancada e sem chave! Agente recua.")
                posicao -= 1
                energia -= 2.0

        elif obstaculo == "extintor disponivel":
            print("    Extintor encontrado! Agente coleta e avança.")
            inventario.append("extintor")
            posicao += 1

        elif obstaculo == "fumaca":
            if "extintor" in inventario:
                print("    Fumaça bloqueando! Agente usa o extintor e passa.")
                inventario.remove("extintor")
                posicao += 1
                energia -= 1.0
            else:
                print("    Fumaça bloqueando! Agente recua para buscar extintor.")
                posicao -= 1
                energia -= 2.0

        elif obstaculo == "livre" or obstaculo == "caminho livre":
            print("    Caminho livre! Agente avança.")
            posicao += 1

        elif obstaculo == "saida":
            print("    SAÍDA ENCONTRADA! Agente está em segurança!")
            posicao += 1

        else:
            print("    Situação desconhecida. Agente perde energia.")
            energia -= 1.0

        print(f"    Energia restante: {energia:.0f}")
        print(f"    Inventário: {inventario if inventario else 'vazio'}")
        print()

    print("=" * 50)
    if posicao == len(locais) - 1:
        print("EVACUAÇÃO BEM-SUCEDIDA! Agente chegou à rua.")
    elif energia <= 0:
        print("FALHA NA EVACUAÇÃO. O agente ficou sem energia.")
    print("=" * 50)

simular_evacuacao()

"""# PARTE 3: Reflexão Crítica

### Mapeando a minha casa, percebi que nunca havia prestado atenção nos obstáculos presentes. Cômodos sem uma boa iluminação, passavam despercebidos no dia a dia. Ao tentar transformar esse trajeto em um código, fui obrigado a enxergar cada detalhe com atenção, o que me fez perceber a importância de se manter prevenido para qualquer situação, pois em caso de emergência não terei mais problemas.

### Ao transformar portas e corredores em lógica de programação, percebi que o pensamento cotidiano costuma ser impreciso. Enquanto no dia a dia agimos de forma vaga, a programação exige respostas claras para cada situação. Isso mostrou que uma prevenção eficiente depende de planejamento detalhado, e não apenas de uma ideia geral de saída.

### Isso me fez perceber que aprender programação também ajuda a organizar o pensamento no dia a dia. Assim como no simulador o agente precisa se preparar antes de enfrentar obstáculos, na vida real também podemos antecipar problemas e pensar em soluções com mais lógica e eficiência.
"""